[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
normal = { family = "MesloLGL Nerd Font", style = "Regular" }
bold   = { family = "MesloLGL Nerd Font", style = "Bold" }
italic = { family = "MesloLGL Nerd Font", style = "Italic" }
size   = 14.0

[window]
opacity = 0.5
blur = true
dimensions = { columns = 130, lines = 35 }

